### ISSUE TITLE
A TorsionDrive record with status "complete" but IndexErrors in get_final_molecules() and get_final_results()

### ISSUE THREAD

**Issue by maxentile** [MolSSI/QCFractal#627] opened 2020-10-20 14:21 UTC
Thank you for developing and maintaining this important and thoughtfully designed resource.

**Describe the bug**
For one `record` in the `"OpenFF Gen 2 Torsion Set 3 Pfizer Discrepancy 2"` dataset, `record.status` is `"COMPLETE"`, and `record.get_final_energies()` returns a result of the anticipated type, but `record.get_final_results()` and `record.get_final_molecules()` raise `IndexError`s.

**To Reproduce**
```python
import qcportal
print('qcportal version:\n', qcportal.__version__)

client = qcportal.FractalClient()

ds = client.get_collection("TorsionDriveDataset", "OpenFF Gen 2 Torsion Set 3 Pfizer Discrepancy 2")
record = ds.get_record("cn1cnc(=o)/[c:4](=[ch:3]/[c:2]2cccc[ch:1]2)/c1=o", specification="default")

# record.status is fine
print('\nrecord.status:\n', record.status)

# record.get_final_energies() is fine
print('\nrecord.get_final_energies():\n', record.get_final_energies())

# IndexError in record.get_final_results()
try:
    record.get_final_results()
except IndexError as e:
    print('\nrecord.get_final_results() error:\n', e)

# IndexError in record.get_final_molecules()
try:
    record.get_final_molecules()
except IndexError as e:
    print('\nrecord.get_final_molecules() error:\n', e)
```

which outputs
```
qcportal version:
 v0.14.0

record.status:
 RecordStatusEnum.complete

record.get_final_energies():
 {(-90,): -724.5923509169016, (-105,): -724.5931056257026, (-75,): -724.593178352678, (-120,): -724.5952233618054, (-60,): -724.5949699655224, (-135,): -724.5971682324434, (-45,): -724.5968672143975, (-150,): -724.5985466363663, (-30,): -724.5981047669392, (-165,): -724.5992074462332, (-15,): -724.5987430916255, (0,): -724.5991603427262, (180,): -724.5991226453838, (15,): -724.5992145396332, (165,): -724.5986395335119, (30,): -724.5986781196046, (150,): -724.5978782286115, (45,): -724.5975412010181, (135,): -724.5964494579872, (60,): -724.5957778019639, (120,): -724.5945162757828, (75,): -724.5935717349693, (105,): -724.5928872856384, (90,): -724.5923581578061}

record.get_final_results() error:
 list index out of range

record.get_final_molecules() error:
 list index out of range
```

**Expected behavior**
For all other TorsionDrive records I've queried whose `status` was `"COMPLETE"`, `record.get_final_energies()`, `record.get_final_results()`, and `record.get_final_molecules()` all returned results of the anticipated type without error.

**Additional context**

More complete error message for `record.get_final_results()`
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
----> 1 record.get_final_results()

.../site-packages/qcportal/models/torsiondrive.py in get_final_results(self, key)
    339         if "final_results" not in self.cache:
    340 
--> 341             map_id_key = self._get_min_optimization_map()
    342             ret = {}
    343 

.../site-packages/qcportal/models/torsiondrive.py in _get_min_optimization_map(self)
    444             k = self._serialize_key(k)
    445             minpos = self.minimum_positions[k]
--> 446             final_opt_id = tasks[minpos]
    447             map_id_key[final_opt_id] = k
    448 

IndexError: list index out of range
```

More complete error message for `record.get_final_molecules()`
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
----> 1 record.get_final_molecules()

.../site-packages/qcportal/models/torsiondrive.py in get_final_molecules(self, key)
    299         if "final_molecules" not in self.cache:
    300 
--> 301             map_id_key = self._get_min_optimization_map()
    302 
    303             opt_ids = list(map_id_key.keys())

.../site-packages/qcportal/models/torsiondrive.py in _get_min_optimization_map(self)
    444             k = self._serialize_key(k)
    445             minpos = self.minimum_positions[k]
--> 446             final_opt_id = tasks[minpos]
    447             map_id_key[final_opt_id] = k
    448 

IndexError: list index out of range
```

**Comment by bennybp** [comment] 2020-10-21 13:53
Thanks for the report! This was reported almost simultaneously privately by someone else, too. My hunch is that there is a bug in the torsiondrive service that results in incorrect indices being recorded. I was already looking at that code, so I will look into it this week.

**Comment by bennybp** [comment] 2020-10-23 01:41
We have found a few times this has happened in the entire database, but they are all about a year old or older. It's likely the underlying issue was fixed at some point (maybe in 7647232afb985fa865f80445c0483635af87bb97). So I am cautiously optimistic that the original bug is fixed.

That leaves fixing the old data. We are currently looking at the best way to do that. It may be reparable because of some redundancy in the data.

**Comment by maxentile** [comment] 2020-10-23 03:35
Thank you for looking into this @bennybp ! This commit looks like it would have fixed the issue, and the record reported here was created before the commit you reference.

**Comment by bennybp** [comment] 2020-10-31 20:56
oops completely missed that this is a duplicate of issue #540 

A comment there mentions a migration as a possible cause. I can look at that as well, but either way we will have to write a script to fix the existing data.

Closing as duplicate. Keep on eye on that issue for updates :)

**Closed by bennybp** 2020-10-31 20:56 UTC
Labels: Bug, Service
